// frontend/src/lib/components/Loader.svelte
<script lang="ts">
	interface Props {
		message?: string;
		size?: 'sm' | 'md' | 'lg';
	}

	let { message = '', size = 'md' }: Props = $props();

	const sizeClasses = {
		sm: 'w-5 h-5 border-2',
		md: 'w-8 h-8 border-3',
		lg: 'w-12 h-12 border-4',
	};
</script>

<div class="flex flex-col items-center justify-center gap-3">
	<div
		class="rounded-full border-primary/30 border-t-primary animate-spin {sizeClasses[size]}"
	></div>
	{#if message}
		<p class="text-text-muted text-sm animate-pulse">{message}</p>
	{/if}
</div>

// frontend/src/components/ui/Loader.tsx
/**
 * Loading spinner component
 */

import { clsx } from 'clsx'

interface LoaderProps {
  size?: 'sm' | 'md' | 'lg'
  message?: string
  className?: string
}

export function Loader({ size = 'md', message, className }: LoaderProps) {
  const sizes = {
    sm: 'w-6 h-6 border-2',
    md: 'w-10 h-10 border-3',
    lg: 'w-16 h-16 border-4',
  }

  return (
    <div className={clsx('flex flex-col items-center gap-4', className)}>
      <div
        className={clsx(
          sizes[size],
          'rounded-full border-midnight-700 border-t-indigo-500 animate-spin'
        )}
      />
      {message && <p className="text-gray-400 text-sm">{message}</p>}
    </div>
  )
}
