// frontend/src/components/ui/StepIndicator.tsx
/**
 * Step indicator for wizard flow
 */

import { Check } from 'lucide-react'
import { clsx } from 'clsx'

interface StepIndicatorProps {
  currentStep: number
  totalSteps: number
}

export function StepIndicator({ currentStep, totalSteps }: StepIndicatorProps) {
  return (
    <div className="flex items-center justify-center gap-1 mb-8">
      {Array.from({ length: totalSteps }, (_, i) => {
        const step = i + 1
        const isActive = step === currentStep
        const isCompleted = step < currentStep

        return (
          <div key={step} className="flex items-center">
            {/* Step circle */}
            <div
              className={clsx(
                'w-8 h-8 rounded-full flex items-center justify-center text-sm font-semibold transition-all duration-200',
                isCompleted && 'bg-emerald-500 text-white',
                isActive && 'bg-indigo-500 text-white shadow-lg shadow-indigo-500/40',
                !isCompleted && !isActive && 'bg-midnight-700 border-2 border-white/10 text-gray-500'
              )}
            >
              {isCompleted ? <Check className="w-4 h-4" /> : step}
            </div>

            {/* Connector line */}
            {step < totalSteps && (
              <div
                className={clsx(
                  'w-6 h-0.5 mx-1',
                  isCompleted ? 'bg-emerald-500' : 'bg-white/10'
                )}
              />
            )}
          </div>
        )
      })}
    </div>
  )
}

// frontend/src/lib/components/StepIndicator.svelte
<script lang="ts">
	import { Check } from 'lucide-svelte';

	interface Props {
		currentStep: number;
		totalSteps?: number;
	}

	let { currentStep, totalSteps = 4 }: Props = $props();

	const steps = $derived(Array.from({ length: totalSteps }, (_, i) => i + 1));
</script>

<div class="mb-6 flex items-center justify-center gap-2">
	{#each steps as step (step)}
		{@const index = step - 1}
		{#if index > 0}
			<!-- Connecting line between steps -->
			<span
				class="h-[3px] max-w-12 flex-1 rounded-full transition-colors duration-300"
				class:bg-success-600={step < currentStep}
				class:bg-primary-600={step === currentStep}
				class:bg-neutral-700={step > currentStep}
			></span>
		{/if}
		<!-- Step circle -->
		<span
			class="flex h-10 w-10 items-center justify-center rounded-full text-sm font-semibold shadow-sm transition-all duration-300 {step ===
			currentStep
				? 'bg-primary-600 text-white ring-4 ring-primary-500/20'
				: step < currentStep
					? 'bg-success-600 text-white'
					: 'border border-neutral-700 bg-neutral-800 text-neutral-400'}"
		>
			{#if step < currentStep}
				<Check size={20} strokeWidth={2.5} />
			{:else}
				{step}
			{/if}
		</span>
	{/each}
</div>
